// Generated by Code/backend: npm run schema:export. Do not edit by hand.

export type PropertyStatus = "DRAFT" | "COMING_SOON" | "ON_SALE" | "SOLD_OUT" | "OFFLINE";

export type PropertyStage = "PLANNING" | "UNDER_CONSTRUCTION" | "READY_TO_MOVE";

export interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  createdAt: string;
}

export interface PropertyMedia {
  id: string;
  url: string;
  type: string;
  isPrimary: boolean;
  sortOrder: number;
  altText: string | null;
  aiJobId: string | null;
}

export interface Feature {
  id: string;
  name: string;
}

export interface PropertyValueHistory {
  id: string;
  year: number;
  value: number;
  growthPercent: number | null;
  isSynthetic: boolean;
  source: string | null;
}

export interface PropertyHistoricalPrice {
  year: number;
  price: number;
}

export interface Property {
  id: string;
  sourceKey: string | null;
  agentId: string | null;
  name: string;
  location: string | null;
  county: string | null;
  address: string | null;
  postalCode: string | null;
  type: string | null;
  saleType: string | null;
  status: PropertyStatus;
  stage: PropertyStage | null;
  priceMin: number | null;
  priceMax: number | null;
  bedroomsMin: number | null;
  bedroomsMax: number | null;
  bathroomsMin: number | null;
  bathroomsMax: number | null;
  sizeSqm: number | null;
  publicationStatus: PublicationStatus;
  publishedAt: string | null;
  slug: string | null;
  developmentId: string | null;
  sizeSqmMax: number | null;
  bedroomOptions: Array<number>;
  bathroomOptions: Array<number>;
  sizeCategory: string | null;
  completionYear: number | null;
  description: string | null;
  agent: User | null;
  media: Array<PropertyMedia>;
  features: Array<Feature>;
  valueHistory: Array<PropertyValueHistory>;
  historicalPrices: Array<PropertyHistoricalPrice>;
  listedDate: string | null;
  createdAt: string;
  updatedAt: string;
  clickCount: number;
  interestCount: number;
  pendingInterestCount: number;
  saveCount: number;
  campaigned: boolean;
}

export interface PropertyFilterInput {
  search?: string | null;
  county?: string | null;
  postalCode?: string | null;
  type?: string | null;
  saleType?: string | null;
  status?: PropertyStatus | null;
  stage?: PropertyStage | null;
  minPrice?: number | null;
  maxPrice?: number | null;
  minBedrooms?: number | null;
  maxBedrooms?: number | null;
  minBathrooms?: number | null;
  maxBathrooms?: number | null;
  completionYear?: number | null;
  location?: string | null;
  listedFrom?: string | null;
  listedTo?: string | null;
  publicationStatus?: PublicationStatus | null;
  sort?: string | null;
  minClicks?: number | null;
  minInterests?: number | null;
  notCampaigned?: boolean | null;
}

export interface PropertyConnection {
  nodes: Array<Property>;
  totalCount: number;
}

export interface Query {
  properties: PropertyConnection;
  property: Property | null;
  page: PageContent | null;
  newsArticles: Array<NewsArticle>;
  newsArticle: NewsArticle | null;
  adminPages: Array<PageContent>;
  adminNews: Array<NewsArticle>;
  adminProperty: Property | null;
  adminProperties: PropertyConnection;
  subscribers: Array<Subscriber>;
  campaigns: Array<Campaign>;
  campaignPreview: CampaignPreview;
  me: User;
  propertyImportUpload: PropertyUpload;
  propertyImportStatus: PropertyImport;
  propertyImportHistory: Array<PropertyImport>;
  adminDashboard: AdminDashboard;
  usersPage: UserConnection;
  agents: Array<User>;
  subscribersPage: SubscriberConnection;
  exportSubscribers: FileDownload;
  campaignsPage: CampaignConnection;
  campaignDetail: Campaign;
  campaignStats: Array<CampaignDay>;
  templatesPage: TemplateConnection;
  templatePreview: HtmlResult;
  interestsPage: InterestConnection;
  interestGroups: Array<InterestGroup>;
  newsPage: NewsConnection;
  publicNewsPage: NewsConnection;
  subscriberImportHistory: Array<PropertyImport>;
  savedProperties: Array<Property>;
  propertyAssistant: PropertyAssistantResult;
}

export type PublicationStatus = "DRAFT" | "PUBLISHED";

export type SubscriberStatus = "PENDING" | "ACTIVE" | "UNSUBSCRIBED";

export type CampaignStatus = "DRAFT" | "QUEUED" | "SENDING" | "SENT" | "PARTIALLY_FAILED" | "FAILED";

export type DeliveryStatus = "PENDING" | "SENDING" | "SENT" | "FAILED" | "SKIPPED";

export interface AuthPayload {
  token: string;
  expiresAt: string;
  user: User;
}

export interface PageMedia {
  id: string;
  url: string;
  altText: string | null;
  sortOrder: number;
}

export interface PageContent {
  id: string;
  slug: string;
  title: string;
  heroHeading: string | null;
  heroText: string | null;
  heroImageUrl: string | null;
  introduction: string | null;
  publicationStatus: PublicationStatus;
  publishedAt: string | null;
  developmentId: string | null;
  gallery: Array<PageMedia>;
  updatedAt: string;
}

export interface NewsArticle {
  id: string;
  externalUrl: string | null;
  title: string;
  summary: string | null;
  content: string | null;
  imageUrl: string | null;
  publicationStatus: PublicationStatus;
  publishedAt: string | null;
  activeFrom: string | null;
  activeUntil: string | null;
  properties: Array<Property>;
  updatedAt: string;
  newsClickCount: number;
  taggedPropertyVisitCount: number;
}

export interface Subscriber {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  status: SubscriberStatus;
  consentGrantedAt: string | null;
  consentVersion: string | null;
  subscribedAt: string | null;
  unsubscribedAt: string | null;
}

export interface SubscriptionResult {
  success: boolean;
}

export interface CampaignRecipient {
  id: string;
  recipientEmail: string;
  recipientName: string;
  status: DeliveryStatus;
  sentAt: string | null;
  failedAt: string | null;
  errorMessage: string | null;
  attemptCount: number;
}

export interface CampaignProperty {
  id: string;
  propertyId: string | null;
  propertyName: string;
}

export interface Campaign {
  id: string;
  subject: string;
  templateHtml: string | null;
  bodyText: string | null;
  renderedHtml: string | null;
  status: CampaignStatus;
  newsArticleId: string | null;
  templateId: string | null;
  sentAt: string | null;
  recipientCount: number;
  recipients: Array<CampaignRecipient>;
  properties: Array<CampaignProperty>;
  createdAt: string;
  completedAt: string | null;
  clickCount: number | null;
  interestCount: number | null;
  saveCount: number | null;
  sentCount: number | null;
  failedCount: number | null;
}

export interface CampaignPreview {
  subject: string;
  html: string;
  consentedRecipientCount: number;
}

export interface PageMediaInput {
  url: string;
  altText?: string | null;
}

export interface PageInput {
  slug: string;
  title: string;
  heroHeading?: string | null;
  heroText?: string | null;
  heroImageUrl?: string | null;
  introduction?: string | null;
  developmentId?: string | null;
  gallery?: Array<PageMediaInput> | null;
}

export interface NewsInput {
  externalUrl?: string | null;
  title: string;
  summary?: string | null;
  content?: string | null;
  imageUrl?: string | null;
  activeFrom?: string | null;
  activeUntil?: string | null;
  propertyIds?: Array<string> | null;
}

export interface HouseTypeInput {
  name: string;
  agentName?: string | null;
  sourceKey?: string | null;
  agentId?: string | null;
  sizeCategory?: string | null;
  completionYear?: number | null;
  features?: Array<string> | null;
  slug?: string | null;
  developmentId?: string | null;
  location?: string | null;
  county?: string | null;
  address?: string | null;
  postalCode?: string | null;
  type?: string | null;
  saleType?: string | null;
  status?: PropertyStatus | null;
  stage?: PropertyStage | null;
  priceMin?: number | null;
  priceMax?: number | null;
  bedroomsMin?: number | null;
  bedroomsMax?: number | null;
  bathroomsMin?: number | null;
  bathroomsMax?: number | null;
  sizeSqm?: number | null;
  sizeSqmMax?: number | null;
  bedroomOptions?: Array<number> | null;
  bathroomOptions?: Array<number> | null;
  description?: string | null;
  listedDate?: string | null;
  historicalPrices?: Array<PropertyHistoricalPrice> | null;
  images?: Array<PageMediaInput> | null;
}

export interface SubscriberInput {
  name: string;
  email: string;
  phone?: string | null;
  consent: boolean;
}

export interface CampaignInput {
  subject: string;
  templateHtml?: string | null;
  bodyText?: string | null;
  newsArticleId?: string | null;
  templateId?: string | null;
  propertyIds?: Array<string> | null;
}

export interface Mutation {
  login: AuthPayload;
  logout: boolean;
  savePage: PageContent;
  publishPage: PageContent;
  deletePage: boolean;
  saveNews: NewsArticle;
  publishNews: NewsArticle;
  deleteNews: boolean;
  saveProperty: Property;
  publishProperty: Property;
  deleteProperty: boolean;
  subscribe: SubscriptionResult;
  unsubscribe: boolean;
  saveCampaign: Campaign;
  uploadPropertyCsv: PropertyUpload;
  validatePropertyCsv: PropertyUpload;
  cancelPropertyUpload: boolean;
  startPropertyImport: PropertyImport;
  createUser: User;
  addSubscriber: Subscriber;
  saveTemplate: CampaignTemplate;
  sendCampaign: Campaign;
  saveFollowUp: InterestFollowUp;
  sendFollowUp: InterestFollowUp;
  submitInterest: Interest;
  uploadPropertyImage: UploadedImage;
  uploadSubscriberFile: PropertyUpload;
  startSubscriberImport: PropertyImport;
  setPropertySaved: boolean;
  recordCampaignSave: boolean;
  recordPropertyView: boolean;
}

export interface CsvHeaderResult {
  valid: boolean;
  expectedColumns: Array<string>;
  requiredColumns: Array<string>;
  receivedColumns: Array<string>;
  missingColumns: Array<string>;
  unknownColumns: Array<string>;
  duplicateColumns: Array<string>;
  emptyColumns: Array<number>;
}

export interface ImportError {
  rowNumber: number;
  field: string;
  value: string | null;
  message: string;
  errorType: string;
}

export interface CsvValidation {
  valid: boolean;
  totalRows: number;
  validRows: number;
  invalidRows: number;
  schema: CsvHeaderResult;
  errors: Array<ImportError>;
  totalErrors: number;
  errorsTruncated: boolean;
  duplicateProperties: Array<{rowNumber:number;name:string;existingPropertyId:string|null;existingPropertyName:string|null;source:string;resolution:string|null}>;
  unresolvedDuplicateCount: number;
}

export interface PropertyUpload {
  id: string;
  filename: string;
  status: string;
  byteSize: number;
  validation: CsvValidation | null;
  expiresAt: string;
}

export interface ImportBatch {
  id: string;
  chunkIndex: number;
  totalRows: number;
  processedRows: number;
  status: string;
  attempts: number;
  lastError: string | null;
}

export interface PropertyImport {
  id: string;
  filename: string;
  status: string;
  createdAt: string;
  startedAt: string | null;
  completedAt: string | null;
  adminName: string;
  totalRows: number;
  totalJobs: number;
  completedJobs: number;
  failedJobs: number;
  waitingJobs: number;
  activeJobs: number;
  retryingJobs: number;
  successfulRows: number;
  failedRows: number;
  percentage: number;
  errorSummary: string | null;
  queueWarning: string | null;
  chunks: Array<ImportBatch>;
  rowErrors: Array<ImportError>;
  errorCount: number;
}

export interface AdminListInput {
  search?: string | null;
  limit?: number | null;
  offset?: number | null;
  from?: string | null;
  to?: string | null;
  sort?: string | null;
}

export interface SubscriberFilter {
  search?: string | null;
  limit?: number | null;
  offset?: number | null;
  status?: SubscriberStatus | null;
}

export interface CampaignFilter {
  search?: string | null;
  limit?: number | null;
  offset?: number | null;
  from?: string | null;
  to?: string | null;
  status?: CampaignStatus | null;
}

export interface InterestFilter {
  search?: string | null;
  limit?: number | null;
  offset?: number | null;
  from?: string | null;
  to?: string | null;
  propertyId?: string | null;
  propertyName?: string | null;
  location?: string | null;
  agentId?: string | null;
  pendingOnly?: boolean | null;
}

export interface CreateUserInput {
  name: string;
  email: string;
  password: string;
  isAdmin: boolean;
}

export type TemplatePurpose = "CAMPAIGN" | "INTEREST_FOLLOW_UP";

export interface TemplateInput {
  name: string;
  subject?: string | null;
  htmlContent: string;
  purpose?: TemplatePurpose | null;
  propertyIds?: Array<string> | null;
}

export interface InterestInput {
  propertyId: string;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  consent: boolean;
  campaignToken?: string | null;
}

export interface FollowUpInput {
  interestId: string;
  subject: string;
  body: string;
  templateId?: string | null;
}

export interface UserConnection {
  nodes: Array<User>;
  totalCount: number;
}

export interface SubscriberConnection {
  nodes: Array<Subscriber>;
  totalCount: number;
  activeCount: number;
  unsubscribedCount: number;
}

export interface SubscriberStats {
  totalSubscribers: number;
  totalUnsubscribers: number;
  averageSubscribersPerDay: number;
  averageUnsubscribersPerDay: number;
  days: Array<{ date: string; registrations: number; activeRegistrations: number; unsubscribes: number }>;
}

export interface CampaignConnection {
  nodes: Array<Campaign>;
  totalCount: number;
}

export interface NewsConnection {
  nodes: Array<NewsArticle>;
  totalCount: number;
}

export interface TemplateConnection {
  nodes: Array<CampaignTemplate>;
  totalCount: number;
}

export interface FileDownload {
  filename: string;
  mimeType: string;
  contentBase64: string;
}

export interface UploadedImage {
  url: string;
  storageKey: string;
  mimeType: string;
}

export interface HtmlResult {
  html: string;
}

export interface AdminDashboard {
  properties: number;
  publishedProperties: number;
  subscribers: number;
  unsubscribers: number;
  campaigns: number;
  sentCampaigns: number;
  interests: number;
  pendingInterests: number;
  news: number;
  users: number;
}

export interface CampaignTemplate {
  id: string;
  name: string;
  subject: string | null;
  htmlContent: string;
  purpose: TemplatePurpose;
  propertyIds: Array<string>;
  createdAt: string;
  updatedAt: string;
}

export interface CampaignDay {
  campaignId: string;
  campaignSubject: string;
  date: string;
  sent: number;
  clicks: number;
  interests: number;
  saves: number;
  unsubscribes: number;
  clickRate: number;
  interestRate: number;
}

export interface InterestProperty {
  id: string;
  name: string;
  location: string | null;
  status: PropertyStatus;
}

export interface InterestAgent {
  id: string;
  name: string;
}

export interface InterestFollowUp {
  id: string;
  interestId: string;
  subject: string;
  body: string;
  status: DeliveryStatus;
  sendRequestedAt: string | null;
  sentAt: string | null;
  failedAt: string | null;
  errorMessage: string | null;
  createdAt: string;
}

export interface Interest {
  id: string;
  propertyId: string;
  name: string;
  email: string;
  phone: string | null;
  message: string | null;
  dataConsent: boolean;
  followUpSent: boolean;
  createdAt: string;
  property: InterestProperty;
  agent: InterestAgent | null;
  followUps: Array<InterestFollowUp>;
}

export interface InterestConnection {
  nodes: Array<Interest>;
  totalCount: number;
  pendingCount: number;
}

export interface InterestStats {
  total: number;
  averagePerDay: number;
  totalFollowUps: number;
  averageFollowUpsPerDay: number;
  days: Array<{ date: string; interests: number; followUps: number }>;
}

export interface InterestGroup {
  property: InterestProperty;
  totalCount: number;
  pendingCount: number;
}

export interface PropertyAssistantResult {
  answer: string;
  filterJson: string;
  totalCount: number;
  properties: Array<Property>;
  sourceIds: Array<string>;
}
