import { useState } from "react";
import { useQuery,useAction } from "../api/useQuery";
import { graphqlRequest } from "../api/graphql";
import type { HomeTour as Tour } from "../api/schemaTypes";
import { Button,Field,Feedback,inputClass } from "./AdminUI";
export default function HomeTour({propertyId}:{propertyId:string}){const [prompt,setPrompt]=useState("");const [url,setUrl]=useState("");const action=useAction();const query=useQuery<{homeTours:Tour[]}>(`query($id:ID!){homeTours(propertyId:$id){id propertyId prompt status reviewStatus error videoUrl providerTaskId createdAt reviewNotes}}`,{id:propertyId},4000);
 const active=query.data?.homeTours.some((t)=>["PENDING","PROCESSING"].includes(t.status));
 return <section className="bg-white p-6 space-y-4"><h2 className="font-display text-xl font-semibold">Property Home Tour</h2><p className="text-sm text-stone">Generate from the property's first image, review the video, then approve it. Approval saves the property as draft for an explicit publish step.</p><Feedback error={action.error||query.error} success={action.success} loading={query.loading}/><Field label="Generation prompt"><textarea className={inputClass} rows={4} maxLength={1500} value={prompt} onChange={(e)=>setPrompt(e.target.value)}/></Field><Button disabled={action.busy||active||!prompt.trim()} onClick={()=>void action.run(async()=>{await graphqlRequest('mutation($id:ID!,$prompt:String!){generateHomeTour(propertyId:$id,prompt:$prompt){id}}',{id:propertyId,prompt});query.reload();},"Generation queued")}>Generate Home Tour</Button>
 {query.data?.homeTours.map((tour)=><article key={tour.id} className="border p-4 space-y-3"><p className="text-sm font-medium">{tour.status} · Review: {tour.reviewStatus}</p><p className="text-xs text-stone">{tour.prompt}</p>{tour.error&&<p role="alert" className="text-red-700 text-sm">{tour.error}</p>}{tour.videoUrl&&<video className="w-full max-h-96 bg-black" controls src={tour.videoUrl}/>}{tour.status==="COMPLETED"&&tour.reviewStatus==="PENDING"&&<div className="flex gap-3">{[true,false].map((approve)=><Button key={String(approve)} disabled={action.busy} onClick={()=>void action.run(async()=>{await graphqlRequest('mutation($id:ID!,$approve:Boolean!){reviewHomeTour(id:$id,approve:$approve){id}}',{id:tour.id,approve});query.reload();},approve?"Tour approved; property is a draft":"Tour rejected")}>{approve?"Approve tour":"Reject tour"}</Button>)}</div>}<Button disabled={!!active} onClick={()=>setPrompt(tour.prompt??"")}>Modify prompt to regenerate</Button></article>)}
 <details><summary className="cursor-pointer text-sm">Replace home-tour video with an existing URL</summary><Field label="Video URL"><input className={inputClass} type="url" value={url} onChange={(e)=>setUrl(e.target.value)}/></Field><Button disabled={action.busy||!url} onClick={()=>void action.run(async()=>{await graphqlRequest('mutation($id:ID!,$url:String!){replacePropertyVideo(propertyId:$id,url:$url){id}}',{id:propertyId,url});setUrl("");},"Video replaced; property is a draft")}>Save Video</Button></details></section>;
}
