import type { PropertyFilterInput } from "../api/schemaTypes";
import { Field,inputClass } from "./AdminUI";
export default function PropertyFilters({value,onChange,metrics=false}:{value:PropertyFilterInput;onChange:(value:PropertyFilterInput)=>void;metrics?:boolean}){
 const set=(key:keyof PropertyFilterInput,v:unknown)=>onChange({...value,[key]:v===""?undefined:v});
 return <div className="bg-white p-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{([['search','Search','text'],['location','Location','text'],['minPrice','Minimum price','number'],['maxPrice','Maximum price','number'],['listedFrom','Listed from','date'],['listedTo','Listed until','date'],['minBedrooms','Minimum bedrooms','number'],['minBathrooms','Minimum bathrooms','number']] as const).map(([key,label,type])=><Field key={key} label={label}><input className={inputClass} type={type} min={type==="number"?0:undefined} value={value[key]??""} onChange={(e)=>set(key,type==="number"&&e.target.value?Number(e.target.value):e.target.value)}/></Field>)}
 <Field label="Sales status"><select className={inputClass} value={value.status??""} onChange={(e)=>set("status",e.target.value)}><option value="">All</option>{["DRAFT","COMING_SOON","ON_SALE","SOLD_OUT","OFFLINE"].map((v)=><option key={v}>{v}</option>)}</select></Field>
 <Field label="Stage"><select className={inputClass} value={value.stage??""} onChange={(e)=>set("stage",e.target.value)}><option value="">All</option>{["PLANNING","UNDER_CONSTRUCTION","READY_TO_MOVE"].map((v)=><option key={v}>{v}</option>)}</select></Field>
 <Field label="Sort"><select className={inputClass} value={value.sort??"latest"} onChange={(e)=>set("sort",e.target.value)}><option value="latest">Latest listed</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option>{metrics&&<><option value="clicks">Most clicks</option><option value="interests">Most interests</option></>}</select></Field>
 {metrics&&<><Field label="Minimum clicks"><input className={inputClass} type="number" min="0" value={value.minClicks??""} onChange={(e)=>set("minClicks",e.target.value?Number(e.target.value):undefined)}/></Field><Field label="Minimum interests"><input className={inputClass} type="number" min="0" value={value.minInterests??""} onChange={(e)=>set("minInterests",e.target.value?Number(e.target.value):undefined)}/></Field><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={value.notCampaigned??false} onChange={(e)=>set("notCampaigned",e.target.checked)}/>Not previously campaigned</label></>}
 </div>;
}
