import type { PropertyFilterInput } from "../api/schemaTypes";
import { Field,inputClass } from "./AdminUI";
export default function PropertyFilters({value,onChange,metrics=false}:{value:PropertyFilterInput;onChange:(value:PropertyFilterInput)=>void;metrics?:boolean}){
 const set=(key:keyof PropertyFilterInput,v:unknown)=>onChange({...value,[key]:v===""?undefined:v});
 return <div className="bg-white p-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{([['search','Search','text'],['location','Location','text'],['postalCode','Postal code','text'],['minPrice','Minimum price','number'],['maxPrice','Maximum price','number'],['minBedrooms','Minimum bedrooms','number'],['maxBedrooms','Maximum bedrooms','number'],['minBathrooms','Minimum bathrooms','number'],['maxBathrooms','Maximum bathrooms','number'],['completionYear','Completion year','number']] as const).map(([key,label,type])=><Field key={key} label={label}><input className={inputClass} type={type} min={type==="number"?0:undefined} value={value[key]??""} onChange={(e)=>set(key,type==="number"&&e.target.value?Number(e.target.value):e.target.value)}/></Field>)}
 <Field label="Property type"><select className={inputClass} value={value.type??""} onChange={(e)=>set("type",e.target.value)}><option value="">All</option><option>House</option><option>Apartment</option></select></Field>
 <Field label="Sale type"><select className={inputClass} value={value.saleType??""} onChange={(e)=>set("saleType",e.target.value)}><option value="">All</option><option>New</option><option>Second hand</option><option>Third hand</option><option>Fourth hand</option></select></Field>
 <Field label="Sales status"><select className={inputClass} value={value.status??""} onChange={(e)=>set("status",e.target.value)}><option value="">All</option><option value="ON_SALE">On Sale</option></select></Field>
 <Field label="Stage"><select className={inputClass} value={value.stage??""} onChange={(e)=>set("stage",e.target.value)}><option value="">All</option><option value="READY_TO_MOVE">Ready to Move-in</option></select></Field>
 <Field label="Sort"><select className={inputClass} value={value.sort??"latest"} onChange={(e)=>set("sort",e.target.value)}><option value="latest">Latest</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option>{metrics&&<><option value="clicks">Most clicks</option><option value="interests">Most interests</option></>}</select></Field>
 {metrics&&<><Field label="Minimum clicks"><input className={inputClass} type="number" min="0" value={value.minClicks??""} onChange={(e)=>set("minClicks",e.target.value?Number(e.target.value):undefined)}/></Field><Field label="Minimum interests"><input className={inputClass} type="number" min="0" value={value.minInterests??""} onChange={(e)=>set("minInterests",e.target.value?Number(e.target.value):undefined)}/></Field><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={value.notCampaigned??false} onChange={(e)=>set("notCampaigned",e.target.checked)}/>Not previously campaigned</label></>}
 </div>;
}
