import { test, expect, type Page } from '@playwright/test';
// Browser journeys intercept every API request. They never contact PostgreSQL,
// Redis, SMTP, or AI, and never upload a CSV to the real application.
const property={id:'fixture-home',name:'Fixture Home',location:'Cork',county:'Cork',address:'Test address',status:'ON_SALE',publicationStatus:'PUBLISHED',publishedAt:'2026-01-01',priceMin:300000,priceMax:350000,type:'House',saleType:'New',bedroomsMin:3,bedroomsMax:3,bathroomsMin:2,bathroomsMax:2,bedroomOptions:[3],bathroomOptions:[2],sizeSqm:100,sizeSqmMax:100,stage:'READY_TO_MOVE',description:'A test-only home.',media:[],features:[],valueHistory:[{year:2023,value:250000},{year:2026,value:300000}],historicalPrices:[{year:2023,price:250000},{year:2026,price:300000}],createdAt:'2026-01-01',listedDate:'2026-01-01',clickCount:0,interestCount:0,saveCount:0,campaigned:false};
const news={id:'fixture-news',title:'Test announcement',summary:'News summary',content:'Published content',publishedAt:'2026-01-01',properties:[property]};
const campaign={id:'fixture-campaign',subject:'Fixture campaign',status:'SENT',createdAt:'2026-01-01',sentAt:'2026-01-01',completedAt:'2026-01-01',recipientCount:4,templateId:null,templateHtml:'<p>Fixture</p>',bodyText:null,properties:[],clickCount:3,interestCount:1,saveCount:2,sentCount:4,failedCount:0};
async function fixture(page:Page,role='USER',signedIn=false){const state={saved:false,interests:[] as Record<string,unknown>[],created:[] as Record<string,unknown>[],filters:[] as Record<string,unknown>[]};
 if(signedIn)await page.addInitScript(()=>sessionStorage.setItem('harborstone-token','mock-session'));
 await page.route('**/graphql',async(route)=>{const {query,variables:v={}}=route.request().postDataJSON();let data:Record<string,unknown>;
 const user={id:'fixture-user',name:'Test User',email:'test@example.test',role,createdAt:'2026-01-01'};
 if(query.includes('login('))data={login:{token:'mock-session',user}};
 else if(query.includes('me{'))data={me:user};
 else if(query.includes('setPropertySaved')){state.saved=v.saved;data={setPropertySaved:state.saved};}
 else if(query.includes('savedProperties'))data={savedProperties:state.saved?[property]:[]};
 else if(query.includes('submitInterest')){state.interests.push(v.input);data={submitInterest:{id:'test-interest'}};}
 else if(query.includes('recordPropertyView'))data={recordPropertyView:true};
 else if(query.includes('campaignsPage'))data={campaignsPage:{nodes:[campaign],totalCount:1}};
 else if(query.includes('campaignStats'))data={campaignStats:[{campaignId:campaign.id,campaignSubject:campaign.subject,date:'2026-01-01',sent:4,clicks:3,interests:1,unsubscribes:1,clickRate:0.75,interestRate:0.25}]};
 else if(query.includes('templatesPage'))data={templatesPage:{nodes:[],totalCount:0}};
 else if(query.includes('propertyAssistant'))data={propertyAssistant:{answer:'Fixture Home has 3 bedrooms in Cork.',filterJson:JSON.stringify({location:'Cork',minBedrooms:3}),totalCount:1,properties:[property],sourceIds:[property.id]}};
 else if(query.includes('publicNewsPage'))data={publicNewsPage:{nodes:[news],totalCount:1}};
 else if(query.includes('newsArticle('))data={newsArticle:news};
 else if(query.includes('usersPage'))data={usersPage:{nodes:[user],totalCount:1}};
 else if(query.includes('createUser')){state.created.push(v.input);data={createUser:{id:'created-user'}};}
 else if(query.includes('propertyImportHistory'))data={propertyImportHistory:[]};
 else if(query.includes('property(id:'))data={property};
 else if(query.includes('properties(')){state.filters.push(v.filter??{});data={properties:{nodes:[property],totalCount:1}};}
 else if(query.includes('logout'))data={logout:true};
 else {await route.fulfill({json:{errors:[{message:'Unmocked operation in isolated test'}]}});return;}
 await route.fulfill({json:{data}});
 });return state;
}
test('public discovery, filters, detail, comparison and history',async({page})=>{const state=await fixture(page);await page.goto('/properties');await page.getByLabel('Location',{exact:true}).fill('Cork');await expect.poll(()=>state.filters.some((f)=>f.location==='Cork')).toBe(true);const compareButton=page.getByRole('button',{name:'+ Compare',exact:true});await expect(compareButton).toBeVisible();await compareButton.click();await page.getByRole('button',{name:'View Fixture Home'}).click();await expect(page.getByRole('heading',{name:'Fixture Home',exact:true})).toBeVisible();await page.goto('/analytics');await page.getByRole('button',{name:'Select properties',exact:true}).click();const analyticsProperty=page.getByRole('dialog').getByRole('button').filter({hasText:'Fixture Home'});await expect(analyticsProperty).toBeVisible();await analyticsProperty.click();await expect(page.getByText('20% since 2023')).toBeVisible();});
test('interest requires consent and submits contact data',async({page})=>{const state=await fixture(page);await page.goto('/properties/fixture-home');await page.getByRole('button',{name:'Register Interest',exact:true}).click();await page.getByPlaceholder('Your full name').fill('Pat');await page.getByPlaceholder('your@email.com').fill('pat@example.test');await page.getByPlaceholder("Tell us what you're looking for...").fill('Please contact me');await page.getByRole('button',{name:'Submit Interest'}).click();await expect(page.getByText('You must consent to data processing')).toBeVisible();expect(state.interests).toHaveLength(0);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Submit Interest'}).click();await expect(page.getByText('Interest Registered!')).toBeVisible();expect(state.interests[0]).toMatchObject({propertyId:'fixture-home',consent:true,email:'pat@example.test'});});
test('USER login, save, saved list, remove and admin denial',async({page})=>{const state=await fixture(page);await page.goto('/login');await page.locator('input[type=email]').fill('test@example.test');await page.locator('input[type=password]').fill('test-password-long');await page.locator('form').getByRole('button',{name:'Sign In',exact:true}).click();await expect(page).toHaveURL(/\/saved$/);await page.goto('/properties');await page.getByTitle('Save property').click();await expect.poll(()=>state.saved).toBe(true);await page.goto('/saved');await expect(page.getByRole('button',{name:'View Fixture Home'})).toBeVisible();await page.getByTitle('Remove from saved').click();await expect(page.getByText('No saved properties yet')).toBeVisible();await page.goto('/admin/users');await expect(page.getByRole('heading',{name:'User Management'})).toHaveCount(0);});
test('mortgage uses selected price and shows repayments',async({page})=>{await fixture(page);await page.goto('/mortgage?price=300000');await expect(page.getByText('€300,000',{exact:true})).toBeVisible();await expect(page.getByText('Monthly Repayment',{exact:true})).toBeVisible();await page.locator('input[type=range]').nth(2).fill('0');await expect(page.getByText('€750',{exact:true})).toBeVisible();});
test('RAG query shows grounded response and applies combined filters',async({page})=>{const state=await fixture(page);await page.goto('/chatbot');await page.getByPlaceholder('Ask about properties, prices, locations...').fill('3 bedrooms in Cork');await page.getByPlaceholder('Ask about properties, prices, locations...').press('Enter');await expect(page.getByText('Fixture Home has 3 bedrooms in Cork.')).toBeVisible();await page.getByRole('link',{name:'Open these filters in property search'}).click();await expect.poll(()=>state.filters.some((f)=>f.location==='Cork'&&f.minBedrooms===3)).toBe(true);});
test('news opens article and related public property',async({page})=>{await fixture(page);await page.goto('/news');await page.getByRole('link',{name:'Test announcement'}).click();await expect(page.getByText('Published content')).toBeVisible();await page.getByRole('link',{name:'Fixture Home',exact:true}).click();await expect(page.getByRole('heading',{name:'Fixture Home',exact:true})).toBeVisible();});
test('admin creates user only after password confirmation matches',async({page})=>{const state=await fixture(page,'ADMIN',true);await page.goto('/admin/users');await page.getByRole('button',{name:'Add User'}).click();await page.getByLabel('Name',{exact:true}).fill('New User');await page.getByLabel('Email',{exact:true}).fill('new@example.test');await page.getByLabel('Password',{exact:true}).fill('a-long-password');await page.getByLabel('Confirm Password',{exact:true}).fill('wrong-password');await page.getByRole('button',{name:'Create User'}).click();await expect(page.getByText('Passwords do not match')).toBeVisible();expect(state.created).toHaveLength(0);await page.getByLabel('Confirm Password',{exact:true}).fill('a-long-password');await page.getByRole('switch').check();await page.getByRole('button',{name:'Create User'}).click();await expect(page.getByText('Account created')).toBeVisible();expect(state.created[0].isAdmin).toBe(true);});
test('campaign log and statistics show attributed metrics',async({page})=>{await fixture(page,'ADMIN',true);await page.goto('/admin/campaigns');await expect(page.getByText('3 clicks · 1 interests · 2 saves')).toBeVisible();await page.getByRole('button',{name:'Statistics',exact:true}).click();await expect(page.getByText('Fixture campaign',{exact:true})).toBeVisible();await expect(page.getByText('75.0%')).toBeVisible();});
test('import page cannot start an import before explicit upload and validation',async({page})=>{await fixture(page,'ADMIN',true);await page.goto('/admin/properties/import');await expect(page.getByRole('button',{name:'Upload File'})).toBeDisabled();await expect(page.getByRole('button',{name:'Start Import'})).toHaveCount(0);await expect(page.getByText('Selecting a file does not upload or import it.',{exact:false})).toBeVisible();});

for(const width of [390,768,1440])test(`public search fits viewport ${width}`,async({page})=>{await fixture(page);await page.setViewportSize({width,height:900});await page.goto('/properties');await expect(page.getByRole('button',{name:'View Fixture Home'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});

