import { useState } from "react";
import { Link } from "react-router-dom";
import { graphqlRequest } from "../../api/graphql";
import { useQuery,useAction } from "../../api/useQuery";
import type { Campaign,CampaignConnection,CampaignDay,CampaignPreview,TemplateConnection } from "../../api/schemaTypes";
import { AdminPage,Button,Field,Feedback,Pager,HtmlPreview,inputClass } from "../../components/AdminUI";
import PropertySelector from "../../components/PropertySelector";
const campaignFields=`id subject status createdAt sentAt completedAt recipientCount templateId templateHtml bodyText properties{id propertyId propertyName}`;
export default function AdminCampaigns(){const [tab,setTab]=useState("log");const [offset,setOffset]=useState(0);const [from,setFrom]=useState("");const [to,setTo]=useState("");const [search,setSearch]=useState("");const [selected,setSelected]=useState<string|null>(null);const [editing,setEditing]=useState<Campaign|null|undefined>();const action=useAction();
 const query=useQuery<{campaignsPage:CampaignConnection}>(`query($input:CampaignFilter){campaignsPage(input:$input){totalCount nodes{${campaignFields} clickCount interestCount saveCount sentCount failedCount}}}`,{input:{from:from||undefined,to:to||undefined,search,offset}},5000);
 if(editing!==undefined)return <CampaignEditor key={editing?.id??"new"} campaign={editing} done={()=>{setEditing(undefined);query.reload();}}/>;
 return <AdminPage title="Email Campaigns" description="Compose, preview and send to consented subscribers; review real delivery results."><div className="flex flex-wrap gap-3"><Button onClick={()=>setTab("log")}>Campaign Log</Button><Button onClick={()=>setTab("stats")}>Statistics</Button><Button onClick={()=>setEditing(null)}>Create Campaign</Button><Link className="border border-navy px-4 py-2 text-sm" to="/admin/templates">Manage Templates</Link></div><div className="grid sm:grid-cols-3 gap-3"><Field label="From"><input type="date" className={inputClass} value={from} onChange={(e)=>{setFrom(e.target.value);setOffset(0);}}/></Field><Field label="To"><input type="date" className={inputClass} value={to} onChange={(e)=>{setTo(e.target.value);setOffset(0);}}/></Field><Field label="Search campaigns"><input className={inputClass} value={search} onChange={(e)=>{setSearch(e.target.value);setOffset(0);}}/></Field></div>
 {tab==="stats"?<Statistics from={from} to={to}/>:<><Feedback error={query.error} loading={query.loading}/><div className="space-y-3">{query.data?.campaignsPage.nodes.map((c)=><article key={c.id} className="bg-white p-5 space-y-3"><div className="flex justify-between gap-3"><h2 className="font-semibold text-lg">{c.subject}</h2><span className="text-sm">{c.status}</span></div><p className="text-xs text-stone">Created {new Date(c.createdAt).toLocaleString()} · Issued {c.sentAt?new Date(c.sentAt).toLocaleString():"Not sent"}</p><p className="text-sm">{c.properties.length} properties: {c.properties.map((p)=>p.propertyName).join(", ")||"None"}</p><p className="text-sm">{c.sentCount??0} sent · {c.failedCount??0} failed · {c.clickCount??0} clicks · {c.interestCount??0} interests · {c.saveCount??0} saves</p><div className="flex gap-3"><Button onClick={()=>setSelected(c.id)}>Recipient results</Button>{c.status==="DRAFT"&&<Button onClick={()=>setEditing(c)}>Edit draft</Button>}<Button className="text-red-700 border-red-700" onClick={()=>{if(window.confirm(`Delete campaign ${c.subject}? This cannot be undone.`))void action.run(async()=>{await graphqlRequest('mutation($id:ID!){deleteCampaign(id:$id)}',{id:c.id});query.reload();},"Campaign deleted");}}>Delete</Button></div></article>)}</div>{!query.loading&&!query.data?.campaignsPage.nodes.length&&<p>No campaigns found.</p>}<Pager offset={offset} total={query.data?.campaignsPage.totalCount??0} onChange={setOffset}/></>}
 {selected&&<Recipients key={selected} id={selected} close={()=>setSelected(null)}/>}</AdminPage>;
}
function Recipients({id,close}:{id:string;close:()=>void}){const [offset,setOffset]=useState(0);const query=useQuery<{campaignDetail:Campaign}>(`query($id:ID!,$offset:Int){campaignDetail(id:$id,offset:$offset){id subject status recipientCount recipients{id recipientEmail recipientName status sentAt failedAt errorMessage attemptCount}}}`,{id,offset},3000);return <section className="border border-amber bg-white p-5 space-y-4"><div className="flex justify-between"><h2 className="text-xl">Recipient results · {query.data?.campaignDetail.subject}</h2><Button onClick={close}>Close</Button></div><Feedback error={query.error} loading={query.loading}/><div className="overflow-auto"><table className="w-full text-sm text-left"><thead><tr>{["Recipient","State","Attempts","Error"].map((h)=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{query.data?.campaignDetail.recipients.map((r)=><tr key={r.id} className="border-t"><td className="p-3">{r.recipientName}<br/>{r.recipientEmail}</td><td>{r.status}</td><td>{r.attemptCount}</td><td>{r.errorMessage}</td></tr>)}</tbody></table></div>{!query.data?.campaignDetail.recipientCount&&<p>No recipients yet.</p>}<Pager size={50} offset={offset} total={query.data?.campaignDetail.recipientCount??0} onChange={setOffset}/></section>;}
function Statistics({from,to}:{from:string;to:string}){const query=useQuery<{campaignStats:CampaignDay[]}>(`query($from:String,$to:String){campaignStats(from:$from,to:$to){campaignId campaignSubject date sent clicks interests saves unsubscribes clickRate interestRate}}`,{from:from||undefined,to:to||undefined});return <section className="space-y-3"><Feedback error={query.error} loading={query.loading}/><p className="text-sm text-stone">Daily UTC totals by campaign; rates use successfully sent emails as the denominator.</p><div className="overflow-auto bg-white"><table className="w-full text-sm text-left"><thead><tr>{["Campaign","Date","Sent","Clicks","Interests","Saves","Unsubscribes","Click / email","Interest / email"].map((h)=><th className="p-3 border-b" key={h}>{h}</th>)}</tr></thead><tbody>{query.data?.campaignStats.map((d)=><tr key={`${d.campaignId}-${d.date}`} className="border-b"><td className="p-3">{d.campaignSubject}</td><td>{d.date}</td><td>{d.sent}</td><td>{d.clicks}</td><td>{d.interests}</td><td>{d.saves}</td><td>{d.unsubscribes}</td><td>{(d.clickRate*100).toFixed(1)}%</td><td>{(d.interestRate*100).toFixed(1)}%</td></tr>)}</tbody></table></div></section>;}
function CampaignEditor({campaign,done}:{campaign:Campaign|null;done:()=>void}){const [id,setId]=useState(campaign?.id);const [subject,setSubject]=useState(campaign?.subject??"");const [propertyIds,setProperties]=useState(campaign?.properties.flatMap((p)=>p.propertyId?[p.propertyId]:[])??[]);const [html,setHtml]=useState(campaign?.templateHtml??"<h1>Property updates</h1><p>Hello {{name}},</p>{{properties}}");const [templateId,setTemplate]=useState(campaign?.templateId??"");const [preview,setPreview]=useState<CampaignPreview|null>(null);const action=useAction();const templates=useQuery<{templatesPage:TemplateConnection}>(`{templatesPage(input:{limit:100}){totalCount nodes{id name subject htmlContent propertyIds}}}`);
 async function save(showPreview:boolean){await action.run(async()=>{const result=await graphqlRequest<{saveCampaign:Campaign}>(`mutation($id:ID,$input:CampaignInput!){saveCampaign(id:$id,input:$input){id}}`,{id,input:{subject,propertyIds,templateHtml:html,templateId:templateId||null}});setId(result.saveCampaign.id);if(showPreview){const data=await graphqlRequest<{campaignPreview:CampaignPreview}>('query($id:ID!){campaignPreview(id:$id){subject html consentedRecipientCount}}',{id:result.saveCampaign.id});setPreview(data.campaignPreview);}else done();});}
 return <AdminPage title={campaign?"Edit Campaign":"Create Campaign"}><Feedback error={action.error||templates.error} success={action.success}/><Field label="Subject"><input className={inputClass} value={subject} onChange={(e)=>{setSubject(e.target.value);setPreview(null);}}/></Field><Field label="Reusable template"><select className={inputClass} value={templateId} onChange={(e)=>{setTemplate(e.target.value);setPreview(null);const t=templates.data?.templatesPage.nodes.find((t)=>t.id===e.target.value);if(t){setHtml(t.htmlContent);setProperties(t.propertyIds);if(t.subject)setSubject(t.subject);}}}><option value="">Custom content</option>{templates.data?.templatesPage.nodes.map((t)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><h2 className="font-semibold">Select published properties</h2><PropertySelector metrics publishedOnly selected={propertyIds} onChange={(ids)=>{setProperties(ids);setPreview(null);}}/><Field label="Email HTML source"><textarea className={`${inputClass} font-mono`} rows={12} spellCheck={false} value={html} onChange={(e)=>{setHtml(e.target.value);setPreview(null);}}/></Field><p className="text-xs text-stone">Include {"{{properties}}"} to render the selected property cards. An unsubscribe link is always appended.</p><div className="flex gap-3"><Button disabled={action.busy||!subject.trim()} onClick={()=>void save(false)}>Save Draft</Button><Button disabled={action.busy||!subject.trim()} onClick={()=>void save(true)}>Save & Preview</Button><Button disabled={action.busy} onClick={done}>Cancel</Button></div>{preview&&<section className="space-y-4"><h2 className="text-xl font-semibold">Review before sending</h2><p>{preview.subject} · {preview.consentedRecipientCount} consented subscribers</p><HtmlPreview html={preview.html}/><Button disabled={action.busy||!preview.consentedRecipientCount} onClick={()=>void action.run(async()=>{await graphqlRequest('mutation($id:ID!){sendCampaign(id:$id){id status}}',{id});done();},"Campaign queued")}>Send Campaign</Button></section>}</AdminPage>;
}
