import { Link } from "react-router-dom";
import { useQuery } from "../../api/useQuery";
import type { AdminDashboard as DashboardData,CampaignDay } from "../../api/schemaTypes";
import { AdminPage,Feedback } from "../../components/AdminUI";
import { AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer } from "recharts";
export default function AdminDashboard(){const {data,loading,error}=useQuery<{adminDashboard:DashboardData;campaignStats:CampaignDay[]}>(`{adminDashboard{properties publishedProperties subscribers unsubscribers campaigns sentCampaigns interests pendingInterests news users} campaignStats{date sent clicks interests saves unsubscribes clickRate interestRate}}`);
  const d=data?.adminDashboard;
  return <AdminPage title="Admin Dashboard" description="Current platform totals and campaign activity from the database."><Feedback error={error} loading={loading}/>{d&&<><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{[["Properties",d.properties,`${d.publishedProperties} published`,"properties"],["Subscribers",d.subscribers,`${d.unsubscribers} unsubscribed`,"subscribers"],["Campaigns",d.campaigns,`${d.sentCampaigns} sent`,"campaigns"],["Interests",d.interests,`${d.pendingInterests} awaiting follow-up`,"interests"],["News",d.news,"Articles and announcements","news"],["Users",d.users,"Platform accounts","users"]].map(([label,value,sub,path])=><Link to={`/admin/${path}`} className="bg-white border-l-4 border-amber p-5 shadow-sm" key={label}><p className="text-xs uppercase text-stone">{label}</p><p className="font-display text-3xl font-bold mt-2">{value}</p><p className="text-xs text-stone mt-2">{sub}</p></Link>)}</div><section className="bg-white p-6"><h2 className="font-semibold mb-4">Campaign activity — last 30 days</h2>{data!.campaignStats.some((r)=>r.sent||r.clicks||r.interests||r.saves)?<ResponsiveContainer width="100%" height={260}><AreaChart data={data!.campaignStats}><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Area dataKey="sent" stroke="#1B2A4A" fill="#1B2A4A20"/><Area dataKey="clicks" stroke="#E8761B" fill="#E8761B20"/><Area dataKey="saves" stroke="#4A6741" fill="#4A674120"/></AreaChart></ResponsiveContainer>:<p className="text-stone py-12 text-center">No campaign activity in this period.</p>}</section></>}</AdminPage>;
}
