import { useState } from "react";
import { graphqlRequest } from "../../api/graphql";
import { useQuery,useAction } from "../../api/useQuery";
import type { Interest,InterestConnection,InterestGroup,InterestFollowUp,User } from "../../api/schemaTypes";
import { AdminPage,Button,Field,Feedback,Pager,inputClass } from "../../components/AdminUI";
export default function AdminInterests(){const [filter,setFilter]=useState({propertyId:"",from:"",to:"",location:"",agentId:"",pendingOnly:false});const [offset,setOffset]=useState(0);const [groupOffset,setGroupOffset]=useState(0);const [contact,setContact]=useState<Interest|null>(null);
 const input={...filter,propertyId:filter.propertyId||undefined,agentId:filter.agentId||undefined,from:filter.from||undefined,to:filter.to||undefined};
 const query=useQuery<{interestsPage:InterestConnection;interestGroups:InterestGroup[];agents:User[]}>(`query($input:InterestFilter,$groups:InterestFilter){interestsPage(input:$input){totalCount pendingCount nodes{id propertyId name email phone message dataConsent followUpSent createdAt property{id name location status} agent{id name} followUps{id interestId subject body status sendRequestedAt sentAt failedAt errorMessage createdAt}}} interestGroups(input:$groups){property{id name location status} totalCount pendingCount} agents{id name email role createdAt}}`,{input:{...input,offset},groups:{...input,offset:groupOffset}},5000);
 const change=(key:string,value:unknown)=>{setFilter({...filter,[key]:value});setOffset(0);setGroupOffset(0);};
 return <AdminPage title="Interests Management" description={`${query.data?.interestsPage.pendingCount??0} awaiting follow-up in this view. History is preserved after contact.`}><Feedback error={query.error} loading={query.loading}/><div className="bg-white p-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{([['propertyId','Property ID','text'],['location','Location','text'],['from','From','date'],['to','To','date']] as const).map(([key,label,type])=><Field key={key} label={label}><input className={inputClass} type={type} value={filter[key]} onChange={(e)=>change(key,e.target.value)}/></Field>)}<Field label="Assigned agent"><select className={inputClass} value={filter.agentId} onChange={(e)=>change("agentId",e.target.value)}><option value="">All agents</option>{query.data?.agents.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={filter.pendingOnly} onChange={(e)=>change("pendingOnly",e.target.checked)}/>Awaiting follow-up only</label><Button onClick={()=>{setFilter({propertyId:"",from:"",to:"",location:"",agentId:"",pendingOnly:false});setOffset(0);setGroupOffset(0);}}>Clear filters</Button></div>
 <section className="space-y-3"><h2 className="font-semibold">Interests by property</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{query.data?.interestGroups.map((g)=><button key={g.property.id} className="bg-white p-4 text-left border-l-4 border-amber" onClick={()=>change("propertyId",g.property.id)}><h3 className="font-semibold">{g.property.name}</h3><p className="text-xs text-stone">{g.property.location} · {g.property.status}</p><p className="text-xl mt-2">{g.totalCount} total</p><p className="text-sm">{g.pendingCount} pending</p></button>)}</div><div className="flex gap-3"><Button disabled={!groupOffset} onClick={()=>setGroupOffset(Math.max(0,groupOffset-20))}>Previous properties</Button><Button disabled={(query.data?.interestGroups.length??0)<20} onClick={()=>setGroupOffset(groupOffset+20)}>More properties</Button></div></section>
 <div className="space-y-3">{query.data?.interestsPage.nodes.map((i)=><article key={i.id} className="bg-white p-5 space-y-2"><div className="flex justify-between gap-3"><h2 className="font-semibold">{i.name} · {i.property.name}</h2><span className="text-sm">{i.followUpSent?"Contacted":"Awaiting follow-up"}</span></div><p className="text-sm">{i.email} · {i.phone||"No phone"}</p><p className="text-xs text-stone">{new Date(i.createdAt).toLocaleString()} · {i.property.location} · {i.agent?.name||"Unassigned"}</p><p className="whitespace-pre-wrap text-sm">{i.message}</p>{i.followUps.map((f)=><p key={f.id} className="text-xs">{f.subject}: {f.sendRequestedAt?f.status:"DRAFT"} {f.errorMessage&&`— ${f.errorMessage}`}</p>)}<Button disabled={!i.dataConsent} onClick={()=>setContact(i)}>Compose email</Button></article>)}</div>{!query.loading&&!query.data?.interestsPage.nodes.length&&<p>No interests match these filters.</p>}<Pager offset={offset} total={query.data?.interestsPage.totalCount??0} onChange={setOffset}/>
 {contact&&<Contact key={contact.id} interest={contact} close={()=>{setContact(null);query.reload();}}/>}</AdminPage>;
}
function Contact({interest,close}:{interest:Interest;close:()=>void}){const draft=interest.followUps.find((f)=>!f.sendRequestedAt);const [id,setId]=useState(draft?.id);const [subject,setSubject]=useState(draft?.subject??`Your interest in ${interest.property.name}`);const [body,setBody]=useState(draft?.body??"Dear {{name}},\n\nThank you for your interest in {{property}}. Please let us know a convenient time to speak.\n\nBest regards,\n{{agent}}");const action=useAction();
 const save=(send:boolean)=>action.run(async()=>{const {saveFollowUp}=await graphqlRequest<{saveFollowUp:InterestFollowUp}>('mutation($id:ID,$input:FollowUpInput!){saveFollowUp(id:$id,input:$input){id}}',{id,input:{interestId:interest.id,subject,body}});setId(saveFollowUp.id);if(send)await graphqlRequest('mutation($id:ID!){sendFollowUp(id:$id){id status}}',{id:saveFollowUp.id});close();},send?"Email queued":"Email draft saved");
 return <section role="dialog" aria-label="Contact interested user" className="bg-white border border-amber p-6 space-y-4"><h2 className="text-xl font-semibold">Email {interest.name}</h2><p className="text-sm">To: {interest.email}</p><Feedback error={action.error}/><Field label="Subject"><input className={inputClass} value={subject} onChange={(e)=>setSubject(e.target.value)}/></Field><Field label="Email content"><textarea className={inputClass} rows={9} value={body} onChange={(e)=>setBody(e.target.value)}/></Field><p className="text-xs text-stone">Supported substitutions: {"{{name}}, {{property}}, {{agent}}"}. The pending-interest count changes only after successful delivery.</p><div className="flex gap-3"><Button disabled={action.busy} onClick={()=>void save(false)}>Save Draft</Button><Button disabled={action.busy||!subject.trim()||!body.trim()} onClick={()=>void save(true)}>Send Email</Button><Button disabled={action.busy} onClick={close}>Cancel</Button></div></section>;
}
