import { useState } from "react";
import { graphqlRequest } from "../../api/graphql";
import { useQuery,useAction } from "../../api/useQuery";
import type { NewsArticle,NewsConnection } from "../../api/schemaTypes";
import { AdminPage,Button,Field,Feedback,Pager,inputClass } from "../../components/AdminUI";
import PropertySelector from "../../components/PropertySelector";
const fields=`id title slug summary content imageUrl publicationStatus publishedAt activeFrom activeUntil updatedAt properties{id name}`;
export default function AdminNewsManager(){const [offset,setOffset]=useState(0);const [search,setSearch]=useState("");const [editing,setEditing]=useState<NewsArticle|null|undefined>();
 const query=useQuery<{newsPage:NewsConnection}>(`query($input:AdminListInput){newsPage(input:$input){totalCount nodes{${fields}}}}`,{input:{search,offset}});const action=useAction();
 if(editing!==undefined)return <NewsEditor key={editing?.id??"new"} article={editing} done={()=>{setEditing(undefined);query.reload();}}/>;
 return <AdminPage title="News Management" description="Create drafts, schedule the active period, and publish announcements."><Feedback error={query.error||action.error} success={action.success} loading={query.loading}/><div className="flex gap-3"><input aria-label="Search news" className={inputClass} placeholder="Search headlines" value={search} onChange={(e)=>{setSearch(e.target.value);setOffset(0);}}/><Button onClick={()=>setEditing(null)}>Add News</Button></div><div className="space-y-4">{query.data?.newsPage.nodes.map((n)=><article key={n.id} className="bg-white p-5 space-y-3"><h2 className="text-xl font-semibold">{n.title}</h2><p className="text-sm">{n.summary}</p><p className="text-xs text-stone">{n.publicationStatus} · Published {n.publishedAt?.slice(0,10)||"—"} · Active {n.activeFrom?.slice(0,10)||"—"} to {n.activeUntil?.slice(0,10)||"no end date"}</p><p className="text-xs">Properties: {n.properties.map((p)=>p.name).join(", ")||"None"}</p><div className="flex gap-3"><Button onClick={()=>setEditing(n)}>Edit</Button><Button disabled={action.busy||n.publicationStatus==="PUBLISHED"} onClick={()=>void action.run(async()=>{await graphqlRequest('mutation($id:ID!){publishNews(id:$id){id}}',{id:n.id});query.reload();},"News published; visibility follows the active dates")}>Publish</Button><Button disabled={action.busy} onClick={()=>{if(window.confirm(`Delete ${n.title}?`))void action.run(async()=>{await graphqlRequest('mutation($id:ID!){deleteNews(id:$id)}',{id:n.id});query.reload();},"News deleted");}}>Delete</Button></div></article>)}</div>{!query.loading&&!query.data?.newsPage.nodes.length&&<p>No news found.</p>}<Pager offset={offset} total={query.data?.newsPage.totalCount??0} onChange={setOffset}/></AdminPage>;
}
function NewsEditor({article,done}:{article:NewsArticle|null;done:()=>void}){const [id,setId]=useState(article?.id);const [form,setForm]=useState({title:article?.title??"",slug:article?.slug??"",summary:article?.summary??"",content:article?.content??"",imageUrl:article?.imageUrl??"",activeFrom:article?.activeFrom?.slice(0,10)??"",activeUntil:article?.activeUntil?.slice(0,10)??"",propertyIds:article?.properties.map((p)=>p.id)??[]});const action=useAction();
 const save=(publish:boolean)=>action.run(async()=>{const {saveNews}=await graphqlRequest<{saveNews:NewsArticle}>(`mutation($id:ID,$input:NewsInput!){saveNews(id:$id,input:$input){id}}`,{id,input:{...form,activeFrom:form.activeFrom||null,activeUntil:form.activeUntil||null}});setId(saveNews.id);if(publish)await graphqlRequest('mutation($id:ID!){publishNews(id:$id){id}}',{id:saveNews.id});done();});
 return <AdminPage title={article?"Edit News":"Add News"}><Feedback error={action.error}/><form className="space-y-5" onSubmit={(e)=>{e.preventDefault();void save(false);}}><div className="bg-white p-6 grid sm:grid-cols-2 gap-4">{([['title','Headline'],['slug','URL slug'],['imageUrl','Cover image URL'],['activeFrom','Go-live date'],['activeUntil','Active until']] as const).map(([key,label])=><Field label={label} key={key}><input className={inputClass} type={key.startsWith("active")?"date":key==="imageUrl"?"url":"text"} required={key==="title"} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></Field>)}{([['summary','Summary'],['content','Content']] as const).map(([key,label])=><Field key={key} label={label}><textarea className={inputClass} rows={key==="content"?8:3} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></Field>)}</div><h2 className="font-semibold">Related properties</h2><PropertySelector selected={form.propertyIds} onChange={(propertyIds)=>setForm({...form,propertyIds})}/><div className="flex gap-3"><Button type="submit" disabled={action.busy}>Save Draft</Button><Button disabled={action.busy||!form.title.trim()} onClick={()=>void save(true)}>Save & Publish</Button><Button disabled={action.busy} onClick={done}>Cancel</Button></div></form></AdminPage>;
}
