import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery,useAction } from "../../api/useQuery";
import { deleteProperty,publishProperties,publishProperty,saveProperty,PROPERTY_FIELDS } from "../../api/properties";
import type { PropertyConnection,PropertyFilterInput,Property,PropertyFilterOptions } from "../../api/schemaTypes";
import { fmt } from "../../data";
import PropertyFilters from "../../components/PropertyFilters";
import { AdminPage,Button,Feedback,Pager } from "../../components/AdminUI";
export default function AdminProperties(){const [filter,setFilter]=useState<PropertyFilterInput>({});const [offset,setOffset]=useState(0);const [view,setView]=useState<Property|null>(null);const [selectedIds,setSelectedIds]=useState<string[]>([]);
 const query=useQuery<{adminProperties:PropertyConnection}>(`query($filter:PropertyFilterInput,$offset:Int){adminProperties(filter:$filter,offset:$offset){totalCount nodes{${PROPERTY_FIELDS}}}}`,{filter,offset});const filterOptions=useQuery<{adminPropertyFilterOptions:PropertyFilterOptions}>("query{adminPropertyFilterOptions{types saleTypes statuses stages}}");const action=useAction();
 const act=(work:()=>Promise<unknown>,message:string)=>action.run(async()=>{await work();query.reload();},message);
 const visibleDraftIds=query.data?.adminProperties.nodes.filter((property)=>property.publicationStatus==="DRAFT").map((property)=>property.id)??[];
 const toggleSelected=(id:string)=>setSelectedIds((selected)=>selected.includes(id)?selected.filter((selectedId)=>selectedId!==id):[...selected,id]);
 const publishSelected=()=>{if(!selectedIds.length||!window.confirm(`Publish ${selectedIds.length} selected ${selectedIds.length===1?"property":"properties"}?`))return;void action.run(async()=>{await publishProperties(selectedIds);setSelectedIds([]);query.reload();},"Selected properties published");};
 return <AdminPage title="Property Management" description={`${query.data?.adminProperties.totalCount??0} properties · drafts are private`}><div className="flex gap-3"><Link className="border border-navy px-4 py-2" to="/admin/properties/import">Bulk Import Properties</Link><Link className="bg-amber text-white px-4 py-2" to="/admin/properties/new">Add Property</Link></div><PropertyFilters value={filter} onChange={(f)=>{setFilter(f);setOffset(0);}} options={filterOptions.data?.adminPropertyFilterOptions}/><label className="text-sm">Publication <select className="border p-2 bg-white" aria-label="Publication" value={filter.publicationStatus??""} onChange={(e)=>{setFilter({...filter,publicationStatus:e.target.value as "DRAFT"|"PUBLISHED"||undefined});setOffset(0);}}><option value="">All</option><option>DRAFT</option><option>PUBLISHED</option></select></label><div className="flex items-center gap-3 flex-wrap bg-white border border-[#ddd5c5] p-3"><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={visibleDraftIds.length>0&&visibleDraftIds.every((id)=>selectedIds.includes(id))} onChange={(e)=>setSelectedIds(e.target.checked?[...new Set([...selectedIds,...visibleDraftIds])]:selectedIds.filter((id)=>!visibleDraftIds.includes(id)))} disabled={!visibleDraftIds.length||action.busy}/>Select visible drafts</label><span className="text-sm text-stone">{selectedIds.length} selected</span><Button disabled={!selectedIds.length||action.busy} onClick={publishSelected}>Publish selected</Button></div><Feedback loading={query.loading} error={query.error||filterOptions.error||action.error} success={action.success}/>
 <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{query.data?.adminProperties.nodes.map((p)=><article className="bg-white border border-[#ddd5c5]" key={p.id}>{p.media.find((m)=>m.type==="IMAGE")&&<img className="w-full h-40 object-cover" src={p.media.find((m)=>m.type==="IMAGE")!.url} alt={p.name} loading="lazy"/>}<div className="p-4 space-y-3">{p.publicationStatus==="DRAFT"&&<label className="text-sm flex items-center gap-2"><input type="checkbox" checked={selectedIds.includes(p.id)} onChange={()=>toggleSelected(p.id)} disabled={action.busy}/>Select draft</label>}<h2 className="font-semibold">{p.name}</h2><p className="text-sm text-stone">{p.location??p.county??"Location not specified"}</p><p>{p.priceMin==null?"Price not set":fmt(p.priceMin)}</p><p className="text-xs">{p.status} · {p.publicationStatus} · {p.stage??"Stage not set"}</p><div className="flex gap-3 flex-wrap text-sm"><Button onClick={()=>setView(p)}>View</Button><Link className="underline py-2" to={`/admin/properties/${p.id}/edit`}>Edit</Link><Button disabled={action.busy} onClick={()=>void act(()=>p.publicationStatus==="DRAFT"?publishProperty(p.id):saveProperty({name:p.name},p.id),p.publicationStatus==="DRAFT"?"Property published":"Property saved as draft")}>{p.publicationStatus==="DRAFT"?"Publish":"Save as draft"}</Button><Button disabled={action.busy} onClick={()=>{if(window.confirm(`Delete ${p.name}? Related records may prevent deletion.`))void act(()=>deleteProperty(p.id),"Property deleted");}}>Delete</Button></div></div></article>)}</div>
 {!query.loading&&!query.data?.adminProperties.nodes.length&&<p>No properties match these filters.</p>}<Pager offset={offset} total={query.data?.adminProperties.totalCount??0} onChange={setOffset}/>
 {view&&<div role="dialog" aria-modal="true" aria-label="Property details" className="fixed inset-0 bg-black/60 z-40 flex items-center justify-center p-6"><section className="bg-white p-6 max-w-2xl max-h-[90vh] overflow-auto space-y-4"><h2 className="text-2xl font-display">{view.name}</h2><p>{view.description||"No description yet"}</p><p>{view.address} {view.postalCode}</p><p>{view.type} · {view.bedroomsMin}–{view.bedroomsMax??view.bedroomsMin} bedrooms · {view.bathroomsMin} bathrooms · {view.sizeSqm} m²</p><p>Completed: {view.completionYear ?? "Not specified"}</p><p>Agent: {view.agent?.name||"Not assigned"}</p><p>{view.features.map((f)=>f.name).join(", ")}</p><Button onClick={()=>setView(null)}>Close</Button></section></div>}
 </AdminPage>;
}
