import { useState } from "react";
import { Link } from "react-router-dom";
import { graphqlRequest } from "../../api/graphql";
import { useQuery,useAction } from "../../api/useQuery";
import type { SubscriberConnection,FileDownload,SubscriberStats } from "../../api/schemaTypes";
import { AdminPage,Button,Field,Feedback,Pager,inputClass } from "../../components/AdminUI";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
export default function AdminSubscribers(){const [status,setStatus]=useState("ALL");const [offset,setOffset]=useState(0);const [search,setSearch]=useState("");const [adding,setAdding]=useState(false);const [form,setForm]=useState({name:"",email:"",phone:"",consent:false});
 const [from,setFrom]=useState("");const [to,setTo]=useState("");
 const query=useQuery<{subscribersPage:SubscriberConnection}>(`query($input:SubscriberFilter){subscribersPage(input:$input){totalCount activeCount unsubscribedCount nodes{id name email phone status subscribedAt unsubscribedAt consentGrantedAt}}}`,{input:{status:status==="ALL"?undefined:status,search,offset}});const action=useAction();
 const stats=useQuery<{subscriberStats:SubscriberStats}>(`query($from:String,$to:String){subscriberStats(from:$from,to:$to){totalSubscribers totalUnsubscribers averageSubscribersPerDay averageUnsubscribersPerDay days{date registrations activeRegistrations unsubscribes}}}`,{from:from||undefined,to:to||undefined});
 const exportFile=()=>action.run(async()=>{const {exportSubscribers:file}=await graphqlRequest<{exportSubscribers:FileDownload}>(`query($status:SubscriberStatus!){exportSubscribers(status:$status){filename mimeType contentBase64}}`,{status});const bytes=Uint8Array.from(atob(file.contentBase64),(c)=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:file.mimeType}));const a=document.createElement("a");a.href=url;a.download=file.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},"Export downloaded");
 return <AdminPage title="Subscribers" description={`${query.data?.subscribersPage.activeCount??0} active · ${query.data?.subscribersPage.unsubscribedCount??0} unsubscribed`}><Feedback loading={query.loading} error={query.error||action.error} success={action.success}/><div className="flex gap-3 flex-wrap"><Button onClick={()=>{setStatus("ACTIVE");setOffset(0);}}>Active</Button><Button onClick={()=>{setStatus("UNSUBSCRIBED");setOffset(0);}}>Unsubscribed</Button><Button onClick={()=>setAdding(!adding)}>Add Subscriber</Button><Link className="border border-navy px-4 py-2 text-sm" to="/admin/subscribers/import">Import CSV / Excel</Link><Button disabled={action.busy} onClick={()=>void exportFile()}>Export {status.toLowerCase()} to Excel</Button></div>
 <section className="bg-white p-5 space-y-4"><div className="flex flex-wrap items-end gap-3"><Field label="From"><input className={inputClass} type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/></Field><Field label="To"><input className={inputClass} type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></Field><div className="bg-cream-dark px-4 py-3"><div className="text-xs text-stone uppercase">Total subscribers</div><div className="text-2xl font-semibold">{stats.data?.subscriberStats.totalSubscribers??0}</div></div><div className="bg-cream-dark px-4 py-3"><div className="text-xs text-stone uppercase">Total unsubscribers</div><div className="text-2xl font-semibold">{stats.data?.subscriberStats.totalUnsubscribers??0}</div></div><div className="bg-cream-dark px-4 py-3"><div className="text-xs text-stone uppercase">Average subscribers/day</div><div className="text-2xl font-semibold">{stats.data?.subscriberStats.averageSubscribersPerDay.toFixed(2)??"0.00"}</div></div><div className="bg-cream-dark px-4 py-3"><div className="text-xs text-stone uppercase">Average unsubscribes/day</div><div className="text-2xl font-semibold">{stats.data?.subscriberStats.averageUnsubscribersPerDay.toFixed(2)??"0.00"}</div></div></div>{stats.data?.subscriberStats.days.length?<div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={stats.data.subscriberStats.days}><CartesianGrid strokeDasharray="3 3" stroke="#ddd5c5"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Line type="monotone" dataKey="activeRegistrations" name="Active registrations" stroke="#4A6741" strokeWidth={3}/><Line type="monotone" dataKey="unsubscribes" name="Unsubscribes" stroke="#6B2B4C" strokeWidth={3}/></LineChart></ResponsiveContainer></div>:<p className="text-sm text-stone">No subscriber activity in this range.</p>}</section>
 {adding&&<form className="bg-white p-6 space-y-4 max-w-xl" onSubmit={(e)=>{e.preventDefault();void action.run(async()=>{await graphqlRequest(`mutation($input:SubscriberInput!){addSubscriber(input:$input){id}}`,{input:form});setForm({name:"",email:"",phone:"",consent:false});setAdding(false);query.reload();},"Subscriber added");}}>{([['name','Name'],['email','Email'],['phone','Phone (optional)']] as const).map(([key,label])=><Field key={key} label={label}><input className={inputClass} type={key==="email"?"email":"text"} required={key!=="phone"} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></Field>)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" required checked={form.consent} onChange={(e)=>setForm({...form,consent:e.target.checked})}/>I have this person's explicit marketing consent.</label><Button type="submit" disabled={action.busy}>Add Subscriber</Button></form>}
 <input aria-label="Search subscribers" className={inputClass} value={search} placeholder="Search name or email" onChange={(e)=>{setSearch(e.target.value);setOffset(0);}}/><div className="bg-white overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Name","Email","Phone","Status","Date"].map((h)=><th className="p-4 border-b" key={h}>{h}</th>)}</tr></thead><tbody>{query.data?.subscribersPage.nodes.map((s)=><tr key={s.id} className="border-b"><td className="p-4">{s.name}</td><td>{s.email}</td><td>{s.phone||"—"}</td><td>{s.status}</td><td>{(s.status==="UNSUBSCRIBED"?s.unsubscribedAt:s.subscribedAt)?.slice(0,10)||"—"}</td></tr>)}</tbody></table>{!query.loading&&!query.data?.subscribersPage.nodes.length&&<p className="p-8">No subscribers match these filters.</p>}</div><Pager offset={offset} total={query.data?.subscribersPage.totalCount??0} onChange={setOffset}/></AdminPage>;
}
