import { useState } from "react";
import { graphqlRequest } from "../../api/graphql";
import { useQuery,useAction } from "../../api/useQuery";
import type { CampaignTemplate,TemplateConnection } from "../../api/schemaTypes";
import { AdminPage,Button,Field,Feedback,Pager,HtmlPreview,inputClass } from "../../components/AdminUI";
import PropertySelector from "../../components/PropertySelector";
export default function Templates(){const [offset,setOffset]=useState(0);const [editing,setEditing]=useState<CampaignTemplate|null|undefined>();const query=useQuery<{templatesPage:TemplateConnection}>(`query($input:AdminListInput){templatesPage(input:$input){totalCount nodes{id name subject htmlContent purpose propertyIds createdAt updatedAt}}}`,{input:{offset}});
 if(editing!==undefined)return <TemplateEditor key={editing?.id??"new"} template={editing} done={()=>{setEditing(undefined);query.reload();}}/>;
 return <AdminPage title="Email Templates" description="Reusable content with a source editor and safe preview."><Feedback error={query.error} loading={query.loading}/><Button onClick={()=>setEditing(null)}>Create Template</Button><div className="space-y-3">{query.data?.templatesPage.nodes.map((t)=><article key={t.id} className="bg-white p-5 flex justify-between items-center"><div><h2 className="font-semibold">{t.name}</h2><p className="text-sm text-stone">{t.purpose} · {t.propertyIds.length} linked properties</p></div><Button onClick={()=>setEditing(t)}>Edit template</Button></article>)}</div>{!query.loading&&!query.data?.templatesPage.nodes.length&&<p>No templates yet.</p>}<Pager offset={offset} total={query.data?.templatesPage.totalCount??0} onChange={setOffset}/></AdminPage>;
}
function TemplateEditor({template,done}:{template:CampaignTemplate|null;done:()=>void}){const [id,setId]=useState(template?.id);const [form,setForm]=useState({name:template?.name??"",subject:template?.subject??"",htmlContent:template?.htmlContent??"<h1>Property updates</h1><p>Hello {{name}},</p>{{properties}}",purpose:template?.purpose??"CAMPAIGN",propertyIds:template?.propertyIds??[]});const [preview,setPreview]=useState("");const action=useAction();
 const save=(showPreview:boolean)=>action.run(async()=>{const {saveTemplate}=await graphqlRequest<{saveTemplate:CampaignTemplate}>(`mutation($id:ID,$input:TemplateInput!){saveTemplate(id:$id,input:$input){id}}`,{id,input:form});setId(saveTemplate.id);if(showPreview){const result=await graphqlRequest<{templatePreview:{html:string}}>('query($id:ID!){templatePreview(id:$id){html}}',{id:saveTemplate.id});setPreview(result.templatePreview.html);}else done();});
 return <AdminPage title={template?"Edit Template":"Create Template"}><Feedback error={action.error} success={action.success}/><Field label="Template name"><input className={inputClass} value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></Field><Field label="Default subject"><input className={inputClass} value={form.subject} onChange={(e)=>setForm({...form,subject:e.target.value})}/></Field><Field label="Purpose"><select className={inputClass} value={form.purpose} onChange={(e)=>setForm({...form,purpose:e.target.value as "CAMPAIGN"|"INTEREST_FOLLOW_UP"})}><option value="CAMPAIGN">Campaign</option><option value="INTEREST_FOLLOW_UP">Interest follow-up</option></select></Field><Field label="Template HTML source"><textarea className={`${inputClass} font-mono`} spellCheck={false} rows={14} value={form.htmlContent} onChange={(e)=>{setForm({...form,htmlContent:e.target.value});setPreview("");}}/></Field><p className="text-xs text-stone">Use {"{{properties}}"} for selected property cards and {"{{name}}"} for the recipient. Every campaign receives an unsubscribe link. Scripts are removed.</p><PropertySelector selected={form.propertyIds} onChange={(propertyIds)=>setForm({...form,propertyIds})}/><div className="flex gap-3"><Button disabled={action.busy||!form.name.trim()} onClick={()=>void save(false)}>Save Template</Button><Button disabled={action.busy||!form.name.trim()} onClick={()=>void save(true)}>Save & Preview</Button><Button disabled={action.busy} onClick={done}>Cancel</Button></div>{preview&&<HtmlPreview html={preview}/>}</AdminPage>;
}
