import { useState } from "react";
import { graphqlRequest } from "../../api/graphql";
import { useQuery,useAction } from "../../api/useQuery";
import type { UserConnection } from "../../api/schemaTypes";
import { AdminPage,Button,Field,Feedback,Pager,inputClass } from "../../components/AdminUI";
export default function Users(){const [offset,setOffset]=useState(0);const [search,setSearch]=useState("");const [adding,setAdding]=useState(false);const [form,setForm]=useState({name:"",email:"",password:"",confirm:"",isAdmin:false});
  const query=useQuery<{usersPage:UserConnection}>(`query($input:AdminListInput){usersPage(input:$input){totalCount nodes{id name email role createdAt}}}`,{input:{search,offset}});const action=useAction();
  async function create(){if(form.password!==form.confirm){action.setError("Passwords do not match");return;}await action.run(async()=>{await graphqlRequest(`mutation($input:CreateUserInput!){createUser(input:$input){id}}`,{input:{name:form.name,email:form.email,password:form.password,isAdmin:form.isAdmin}});setForm({name:"",email:"",password:"",confirm:"",isAdmin:false});setAdding(false);query.reload();},"Account created");}
  return <AdminPage title="User Management" description="Create platform accounts and assign the appropriate role."><Feedback error={action.error||query.error} success={action.success} loading={query.loading}/><div className="flex gap-3"><input aria-label="Search users" className={inputClass} value={search} placeholder="Search name or email" onChange={(e)=>{setSearch(e.target.value);setOffset(0);}}/><Button onClick={()=>setAdding(true)}>Add User</Button></div>
    {adding&&<form className="bg-white p-6 space-y-4 max-w-xl" onSubmit={(e)=>{e.preventDefault();void create();}}><h2 className="text-xl font-semibold">Add User</h2>{([['name','Name'],['email','Email'],['password','Password'],['confirm','Confirm Password']] as const).map(([key,label])=><Field key={key} label={label}><input className={inputClass} type={key==="email"?"email":key==="name"?"text":"password"} required minLength={key==="password"?12:undefined} maxLength={key==="password"?128:undefined} autoComplete={key==="password"||key==="confirm"?"new-password":undefined} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></Field>)}<label className="flex items-center gap-3"><input type="checkbox" role="switch" checked={form.isAdmin} onChange={(e)=>setForm({...form,isAdmin:e.target.checked})}/>Administrator</label><p className="text-xs text-stone">Passwords require 12–128 characters. Administrator access includes managing users and sending campaigns.</p><div className="flex gap-3"><Button type="submit" disabled={action.busy}>Create User</Button><Button disabled={action.busy} onClick={()=>{setAdding(false);setForm({name:"",email:"",password:"",confirm:"",isAdmin:false});}}>Cancel</Button></div></form>}
    <div className="bg-white overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Name","Email","Role","Created"].map((h)=><th key={h} className="p-4 border-b">{h}</th>)}</tr></thead><tbody>{query.data?.usersPage.nodes.map((u)=><tr key={u.id} className="border-b"><td className="p-4">{u.name}</td><td>{u.email}</td><td><span className={u.role==="ADMIN"?"text-amber font-semibold":"text-stone"}>{u.role}</span></td><td>{new Date(u.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{!query.loading&&!query.data?.usersPage.nodes.length&&<p className="p-8">No users found.</p>}</div><Pager offset={offset} total={query.data?.usersPage.totalCount??0} onChange={setOffset}/></AdminPage>;
}
