import { useState } from "react";
import { Link,useParams } from "react-router-dom";
import { graphqlRequest } from "../api/graphql";
import { useQuery } from "../api/useQuery";
import type { NewsArticle,NewsConnection } from "../api/schemaTypes";
import { Feedback,Pager } from "../components/AdminUI";
const fields=`id title externalUrl summary content imageUrl publishedAt activeFrom properties{id name}`;
const recordNewsClick=(id:string)=>{void graphqlRequest("mutation($id:ID!){recordNewsClick(newsArticleId:$id)}",{id}).catch(()=>{});};
const recordPropertyVisit=(newsArticleId:string,propertyId:string)=>{void graphqlRequest("mutation($newsArticleId:ID!,$propertyId:ID!){recordNewsPropertyVisit(newsArticleId:$newsArticleId,propertyId:$propertyId)}",{newsArticleId,propertyId}).catch(()=>{});};
export default function News(){const {id}=useParams();const [offset,setOffset]=useState(0);const query=useQuery<{publicNewsPage?:NewsConnection;newsArticle?:NewsArticle|null}>(id?`query($id:ID!){newsArticle(id:$id){${fields}}}`:`query($input:AdminListInput){publicNewsPage(input:$input){totalCount nodes{${fields}}}}`,id?{id}:{input:{offset,limit:12}});const articles=id?(query.data?.newsArticle?[query.data.newsArticle]:[]):query.data?.publicNewsPage?.nodes??[];
return <div className="bg-cream min-h-screen"><header className="bg-navy text-white px-6 py-10"><div className="max-w-5xl mx-auto"><h1 className="font-display text-3xl font-bold">Latest News</h1><p className="text-white/60 text-sm mt-2">Updates from Harborstone Homes</p></div></header><div className="max-w-5xl mx-auto px-6 py-10 space-y-8"><Feedback error={query.error} loading={query.loading}/>{articles.map((a)=><article key={a.id} className="grid md:grid-cols-2 gap-8">{a.imageUrl&&<img src={a.imageUrl} alt={a.title} className="w-full max-h-80 object-cover"/>}<div className="space-y-4"><p className="text-xs text-stone">{a.publishedAt?.slice(0,10)}</p><h2 className="font-display text-2xl font-bold">{a.externalUrl&&!id?<a href={a.externalUrl} target="_blank" rel="noreferrer" onClick={()=>recordNewsClick(a.id)}>{a.title}</a>:<Link to={`/news/${a.id}`} onClick={()=>recordNewsClick(a.id)}>{a.title}</Link>}</h2><p className="text-stone">{a.summary}</p>{a.content&&<p className={id?"whitespace-pre-wrap":"whitespace-pre-wrap line-clamp-4"}>{a.content}</p>}{a.externalUrl&&id&&<a className="inline-block border px-3 py-2 text-sm" href={a.externalUrl} target="_blank" rel="noreferrer" onClick={()=>recordNewsClick(a.id)}>Read full article</a>}<div className="flex gap-3 flex-wrap">{a.properties.map((p)=><Link key={p.id} className="border px-3 py-1 text-sm" to={`/properties/${p.id}`} onClick={()=>recordPropertyVisit(a.id,p.id)}>{p.name}</Link>)}</div></div></article>)}{!query.loading&&!articles.length&&<p className="text-center py-16">{id?"This article is not available.":"No news published yet."}</p>}{!id&&<Pager offset={offset} size={12} total={query.data?.publicNewsPage?.totalCount??0} onChange={setOffset}/>}</div></div>;}
